#!/usr/bin/env bash
# Rebuild this checkout's install and regenerate calibrations/materials-map.cbor
# for the geometry at the current HEAD, then stamp provenance next to it.
#
# Why: calibrations/ is gitignored, so the map here is a local artifact with no
# recorded relation to the geometry that produced it. A map generated before a
# geometry commit silently gives the CKF the wrong material budget -- eicrecon
# resolves calibrations/materials-map.cbor relative to the working directory and
# will happily use a stale one.
#
# Campaign runs do NOT depend on this file: they snapshot the detector and
# generate their own map (see presentation*/launch_*_dvcs_pcurve.sh). This is
# for ad-hoc runs launched from inside this repo.
#
# Usage: scripts/refresh_local_material_map.sh [--nevents N] [--nparticles N]
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG="${CONFIG:-epic_ip6_extended}"
SIF="${SIF:-/home/tomble/eic/local/lib/eic_xl-26.04.0-stable.sif}"
DETECTOR_CACHE="${DETECTOR_CACHE:-/nas/nas1/tomble/detector_cache_material_maps}"
BUILD_JOBS="${BUILD_JOBS:-$(nproc)}"
NEVENTS="${MATERIAL_NEVENTS:-1000}"
NPARTICLES="${MATERIAL_NPARTICLES:-5000}"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --nevents) NEVENTS="$2"; shift 2 ;;
    --nparticles) NPARTICLES="$2"; shift 2 ;;
    *) echo "unknown argument: $1" >&2; exit 2 ;;
  esac
done

[[ -f "$SIF" ]] || { echo "missing container: $SIF" >&2; exit 3; }

HEAD_SHA="$(git -C "$REPO" rev-parse HEAD)"
WORKDIR="$REPO/build/material_map_refresh"
rm -rf "$WORKDIR"
mkdir -p "$WORKDIR" "$DETECTOR_CACHE"

echo "[$(date -Is)] === build + install $REPO @ ${HEAD_SHA:0:9} ==="
singularity exec "$SIF" bash -lc '
  set -euo pipefail
  repo="$1"; jobs="$2"
  cd "$repo"
  cmake -S . -B build -DCMAKE_INSTALL_PREFIX="$repo/install" >/dev/null
  cmake --build build -j "$jobs"
  cmake --install build >/dev/null
' bash "$REPO" "$BUILD_JOBS"

echo "[$(date -Is)] === geantino scan ($NEVENTS x $NPARTICLES) ==="
singularity exec "$SIF" bash -lc '
  set -euo pipefail
  repo="$1"; config="$2"; workdir="$3"; cache="$4"; nevents="$5"; nparticles="$6"
  cd "$workdir"
  source "$repo/install/bin/thisepic.sh" "$config"
  [[ "$DETECTOR_PATH" == "$repo/install/share/epic" ]] \
    || { echo "DETECTOR_PATH mismatch: $DETECTOR_PATH" >&2; exit 16; }
  export DETECTOR_CACHE="$cache"
  export DETECTOR_CONFIG="$config"
  cp -a "$repo/scripts/material_map/." .
  sed -i "s|^DETECTOR_CONFIG=\"epic_craterlake_material_map\"|DETECTOR_CONFIG=\"\${DETECTOR_CONFIG:-epic_craterlake_material_map}\"|" \
    run_material_map_validation.sh
  rm -f ./*.root geometry-map.json config-map.json config-map_regenerated.json material-map.cbor
  rm -rf plots Validation Surfaces calibrations
  ./run_material_map_validation.sh --nevents "$nevents" --nparticles "$nparticles"
' bash "$REPO" "$CONFIG" "$WORKDIR" "$DETECTOR_CACHE" "$NEVENTS" "$NPARTICLES"

MAP="$WORKDIR/material-map.cbor"
[[ -s "$MAP" ]] || { echo "no map produced at $MAP" >&2; exit 4; }

install -D -m 0644 "$MAP" "$REPO/calibrations/materials-map.cbor"
install -D -m 0644 "$MAP" "$REPO/install/share/epic/calibrations/materials-map.cbor"

SHA="$(sha256sum "$MAP" | cut -d' ' -f1)"
cat >"$REPO/calibrations/materials-map.provenance" <<PROV
# Generated by scripts/refresh_local_material_map.sh -- do not hand-edit.
generated_utc=$(date -u +%Y-%m-%dT%H:%M:%SZ)
epic_commit=$HEAD_SHA
epic_dirty=$(git -C "$REPO" status --porcelain -- compact src | grep -c . || true)
detector_config=$CONFIG
geantino_events=$NEVENTS
geantino_particles=$NPARTICLES
container=$SIF
sha256=$SHA
last_geometry_commit=$(git -C "$REPO" log -1 --format=%H -- compact src)
last_geometry_date=$(git -C "$REPO" log -1 --format=%cI -- compact src)
PROV

echo "[$(date -Is)] === installed map sha256=$SHA ==="
cat "$REPO/calibrations/materials-map.provenance"
